### ISSUE TITLE
Bad names when creating forecasts

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#303] opened 2021-01-23 06:45 UTC
``` r
library(fpp3)
#> ── Attaching packages ─────────────────────────────────────── fpp3 0.3.0.9000 ──
#> ✓ tibble      3.0.5          ✓ tsibble     0.9.3     
#> ✓ dplyr       1.0.3          ✓ tsibbledata 0.2.0     
#> ✓ tidyr       1.1.2          ✓ feasts      0.1.6.9000
#> ✓ lubridate   1.7.9.2        ✓ fable       0.2.1.9000
#> ✓ ggplot2     3.3.3
#> ── Conflicts ───────────────────────────────────────────────── fpp3_conflicts ──
#> x lubridate::date()   masks base::date()
#> x dplyr::filter()     masks stats::filter()
#> x tsibble::interval() masks lubridate::interval()
#> x dplyr::lag()        masks stats::lag()

tidy_bricks <- aus_production %>%
  filter(!is.na(Bricks))
dcmp <- tidy_bricks %>%
  model(stl = STL(log(Bricks) ~ season(window = "periodic"))) %>% 
  components()
dcmp %>%
  model(naive = NAIVE(season_adjust)) %>%
  forecast(h = "5 years")
#> Error: Failed to create output due to bad names.
#> * Choose another strategy with `names_repair`
```

<sup>Created on 2021-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.10
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
#>  [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
#>  [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#>  [1] fable_0.2.1.9000      feasts_0.1.6.9000     fabletools_0.3.0.9000
#>  [4] tsibbledata_0.2.0     tsibble_0.9.3         ggplot2_3.3.3        
#>  [7] lubridate_1.7.9.2     tidyr_1.1.2           dplyr_1.0.3          
#> [10] tibble_3.0.5          fpp3_0.3.0.9000      
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6           progressr_0.7.0      pillar_1.4.7        
#>  [4] compiler_4.0.3       highr_0.8            tools_4.0.3         
#>  [7] digest_0.6.27        anytime_0.3.9        evaluate_0.14       
#> [10] lifecycle_0.2.0      gtable_0.3.0         pkgconfig_2.0.3     
#> [13] rlang_0.4.10         cli_2.2.0            rstudioapi_0.13     
#> [16] yaml_2.2.1           xfun_0.20            withr_2.4.0         
#> [19] stringr_1.4.0        knitr_1.30           generics_0.1.0      
#> [22] vctrs_0.3.6          grid_4.0.3           tidyselect_1.1.0    
#> [25] glue_1.4.2           R6_2.5.0             fansi_0.4.2         
#> [28] distributional_0.2.1 rmarkdown_2.6        farver_2.0.3        
#> [31] purrr_0.3.4          magrittr_2.0.1       scales_1.1.1        
#> [34] ellipsis_0.3.1       htmltools_0.5.1      assertthat_0.2.1    
#> [37] colorspace_2.0-0     renv_0.12.5          stringi_1.5.3       
#> [40] munsell_0.5.0        crayon_1.3.4.9000
```

</details>

**Comment by mitchelloharawild** [comment] 2021-01-24 23:23
Duplicate of #275

**Closed by mitchelloharawild** 2021-01-24 23:23 UTC
