### ISSUE TITLE
Allow NAs in fabletools:::autoplot.fbl_ts

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#290] opened 2020-11-19 05:44 UTC
``` r
library(fpp3)

# Re-index data to allow skip over missing values
calls <- bank_calls %>%
  mutate(t = row_number()) %>%
  update_tsibble(index = t, regular = TRUE) 
# STL decomposition on square root
my_dcmp_spec <- decomposition_model(
  STL(sqrt(Calls) ~ season(period=169) + season(period=5*169), robust=TRUE),
  ETS(season_adjust ~ season("N"))
)
# Compute forecasts and add in correct timestamps
fc <- bank_calls %>% 
  new_data(n=7*24*60/5) %>%
  mutate(time = format(DateTime, format="%H:%M:%S")) %>%
  filter(
    time %in% format(bank_calls$DateTime, format="%H:%M:%S"),
    wday(DateTime, week_start = 1) <= 5
  ) %>%
  mutate(t = row_number() + max(calls$t)) %>%
  left_join(
    calls %>% model(my_dcmp_spec) %>% forecast(h = 5*169), 
    by="t"
  ) %>%
  as_fable(response = "Calls", distribution=Calls) 

# Forecasts 
fc %>% 
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
#> Warning: Removed 84 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/kfYq92D.png)

``` r
# Adding in gaps
fc %>%
  fill_gaps() %>%
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
#> Don't know how to automatically pick scale for object of type tbl_ts/tbl_df/tbl/data.frame. Defaulting to continuous.
#> Error: Aesthetics must be either length 1 or the same as the data (1321): y
```

![](https://i.imgur.com/8tP1RJW.png)

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment] 2020-11-19 06:01
This can/should be improved in `{distributional}` and `{fabletools}`.

The issue is not with `autoplot(<fable>)`, but with `fill_gaps()` and the default fill value for distributions.

There isn't a method for `fill_gaps(<fable>)` at the moment, and so the result gives a tsibble. Additionally, the distribution produced by `fill_gaps()` is invalid (NULL), instead of `dist_missing()`. A method should be added for `fill_gaps(<fable>)` (and `fill_gaps(<dable>)`), and the default fill value for distributions should be `dist_missing()`.

``` r
library(fpp3)
#> ── Attaching packages ────────────────────────────────────────────── fpp3 0.3 ──
#> ✓ tibble      3.0.4          ✓ tsibble     0.9.3.9000
#> ✓ dplyr       1.0.2          ✓ tsibbledata 0.2.0     
#> ✓ tidyr       1.1.2          ✓ feasts      0.1.5.9000
#> ✓ lubridate   1.7.9.2        ✓ fable       0.2.1.9000
#> ✓ ggplot2     3.3.2
#> ── Conflicts ───────────────────────────────────────────────── fpp3_conflicts ──
#> x lubridate::date()   masks base::date()
#> x dplyr::filter()     masks stats::filter()
#> x tsibble::interval() masks lubridate::interval()
#> x dplyr::lag()        masks stats::lag()

# Re-index data to allow skip over missing values
calls <- bank_calls %>%
  mutate(t = row_number()) %>%
  update_tsibble(index = t, regular = TRUE) 
# STL decomposition on square root
my_dcmp_spec <- decomposition_model(
  STL(sqrt(Calls) ~ season(period=169) + season(period=5*169), robust=TRUE),
  ETS(season_adjust ~ season("N"))
)
# Compute forecasts and add in correct timestamps
fc <- bank_calls %>% 
  new_data(n=7*24*60/5) %>%
  mutate(time = format(DateTime, format="%H:%M:%S")) %>%
  filter(
    time %in% format(bank_calls$DateTime, format="%H:%M:%S"),
    wday(DateTime, week_start = 1) <= 5
  ) %>%
  mutate(t = row_number() + max(calls$t)) %>%
  left_join(
    calls %>% model(my_dcmp_spec) %>% forecast(h = 5*169), 
    by="t"
  ) %>%
  as_fable(response = "Calls", distribution=Calls) 

# Forecasts 
fc %>% 
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
#> Warning: Removed 84 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/t5KJq2I.png)

``` r
fc %>%
  fill_gaps(Calls = `dimnames<-`(distributional::dist_missing(1), "Calls")) %>%
  as_fable(response = "Calls", distribution = Calls) %>% 
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
#> Warning: Removed 84 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/dEEAwEW.png)

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment] 2020-12-17 13:01
Closing as `fill_gaps(<fable>)` has been added, and the default missing value for distributions is now improved.

**Comment by robjhyndman** [comment] 2020-12-18 02:25
I was expecting this to work with the update:

```r
fc %>%
  fill_gaps() %>%
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
```

But `fill_gaps()` is returning a `tsibble` rather than a `fable` object.

**Comment by mitchelloharawild** [comment] 2020-12-18 02:42
Fixed, thanks. I had incorrectly assumed `vec_restore(<fable>)` was implemented. There was also an issue with `{distributional}` not inheriting default distribution methods (used for `hilo()`) for missing distributions.

``` r
library(fpp3)
#> ── Attaching packages ────────────────────────────────────────────── fpp3 0.3 ──
#> ✓ tibble      3.0.4          ✓ tsibble     0.9.3.9000
#> ✓ dplyr       1.0.2          ✓ tsibbledata 0.2.0     
#> ✓ tidyr       1.1.2          ✓ feasts      0.1.5.9000
#> ✓ lubridate   1.7.9.2        ✓ fable       0.2.1.9000
#> ✓ ggplot2     3.3.2
#> ── Conflicts ───────────────────────────────────────────────── fpp3_conflicts ──
#> x lubridate::date()   masks base::date()
#> x dplyr::filter()     masks stats::filter()
#> x tsibble::interval() masks lubridate::interval()
#> x dplyr::lag()        masks stats::lag()

# Re-index data to allow skip over missing values
calls <- bank_calls %>%
  mutate(t = row_number()) %>%
  update_tsibble(index = t, regular = TRUE) 
# STL decomposition on square root
my_dcmp_spec <- decomposition_model(
  STL(sqrt(Calls) ~ season(period=169) + season(period=5*169), robust=TRUE),
  ETS(season_adjust ~ season("N"))
)
# Compute forecasts and add in correct timestamps
fc <- bank_calls %>% 
  new_data(n=7*24*60/5) %>%
  mutate(time = format(DateTime, format="%H:%M:%S")) %>%
  filter(
    time %in% format(bank_calls$DateTime, format="%H:%M:%S"),
    wday(DateTime, week_start = 1) <= 5
  ) %>%
  mutate(t = row_number() + max(calls$t)) %>%
  left_join(
    calls %>% model(my_dcmp_spec) %>% forecast(h = 5*169), 
    by="t"
  ) %>%
  as_fable(response = "Calls", distribution=Calls) 

# Forecasts 
fc %>%
  fill_gaps() %>%
  autoplot(bank_calls %>% fill_gaps() %>% filter(yearmonth(DateTime) >= yearmonth("2003 Oct")))
#> Warning: Removed 84 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/f87r2Xn.png)

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by mitchelloharawild** 2020-12-18 02:42 UTC
